# .gitlab-ci.yml

stages:
  - clone
  - build
  - push
  - deploy

variables:
  REGISTRY: kmn1624/craftista
  DOCKER_DRIVER: overlay2
  KUBE_CONFIG: /root/.kube/config

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

clone_source:
  stage: clone
  image: alpine/git
  script:
    - git clone https://github.com/kmn1625/craftista.git source-code
  artifacts:
    paths:
      - source-code

build_frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd source-code/frontend
    - docker build -t $REGISTRY-frontend:latest .

build_catalogue:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd source-code/catalogue
    - docker build -t $REGISTRY-catalogue:latest .

build_voting:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd source-code/voting
    - chmod +x gradlew
    - ./gradlew build --no-daemon
    - docker build -t $REGISTRY-voting:latest .

build_recommendation:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd source-code/recommendation
    - docker build -t $REGISTRY-recommendation:latest .

push_images:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push $REGISTRY-frontend:latest
    - docker push $REGISTRY-catalogue:latest
    - docker push $REGISTRY-voting:latest
    - docker push $REGISTRY-recommendation:latest

deploy_to_k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config
    - kubectl apply -f k8s-manifests/frontend.yaml
    - kubectl apply -f k8s-manifests/catalogue.yaml
    - kubectl apply -f k8s-manifests/voting.yaml
    - kubectl apply -f k8s-manifests/recommendation.yaml
