# k8s-manifests/voting.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
        - name: voting
          image: registry.gitlab.com/kmn1625/craftista_auto/voting:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: voting
spec:
  selector:
    app: voting
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

