name: Build and Push Docker Images

on:
  push:
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          services=(frontend catalogue recommendation voting)
          for svc in "${services[@]}"; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$svc:latest ./services/$svc
            docker push ${{ secrets.DOCKER_USERNAME }}/$svc:latest
          done
