name: Docker Build & Push

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  docker_build_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, catalogue, voting, recommendation]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image for ${{ matrix.service }}
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/craftista:${{ matrix.service }}-latest"
          DOCKERFILE="Dockerfile.${{ matrix.service }}"
          echo "[INFO] Building and pushing $IMAGE_NAME using $DOCKERFILE"
          docker build -t $IMAGE_NAME -f $DOCKERFILE .
          docker push $IMAGE_NAME
