name: Docker Build & Push

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  docker_build_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Images
        run: |
          echo "[INFO] Starting Docker build and push..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/craftista:frontend-latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/craftista:frontend-latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/craftista:catalogue-latest ./catalogue
          docker push ${{ secrets.DOCKER_USERNAME }}/craftista:catalogue-latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/craftista:voting-latest ./voting
          docker push ${{ secrets.DOCKER_USERNAME }}/craftista:voting-latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/craftista:recommendation-latest ./recommendation
          docker push ${{ secrets.DOCKER_USERNAME }}/craftista:recommendation-latest
