name: Build and Push Docker Images

on:
  push:
    paths:
      - 'Dockerfile'
      - 'frontend/**'
      - 'catalogue/**'
      - 'voting/**'
      - 'recommendation/**'
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Infra-State Branch
        run: |
          git fetch origin infra-state
          git checkout infra-state -- infra-state/
          ls -l infra-state

      - name: Move Artifacts to Infra Folder
        run: |
          mkdir -p infra
          cp infra-state/instance_ips.txt infra/
          cp infra-state/k8s-key.pem infra/
          chmod 600 infra/k8s-key.pem

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Images
        run: |
          docker build -t $REGISTRY:frontend-latest ./frontend
          docker push $REGISTRY:frontend-latest
          docker build -t $REGISTRY:catalogue-latest ./catalogue
          docker push $REGISTRY:catalogue-latest
          docker build -t $REGISTRY:voting-latest ./voting
          docker push $REGISTRY:voting-latest
          docker build -t $REGISTRY:recommendation-latest ./recommendation
          docker push $REGISTRY:recommendation-latest
