name: Deploy to Kubernetes

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy_k8s.yaml'
  workflow_dispatch:

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Infra Files
        run: |
          git fetch origin infra-state
          git checkout infra-state -- infra/
          ls -l infra/

      - name: Setup SSH
        run: |
          chmod 600 infra/k8s-key.pem

      - name: Deploy Manifests to Master Node
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}/craftista
        run: |
          MASTER_IP=$(sed -n '1p' infra/instance_ips.txt)
          echo "[INFO] Deploying to Master: $MASTER_IP"
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no -r k8s ubuntu@$MASTER_IP:/home/ubuntu/
          ssh -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "kubectl apply -f /home/ubuntu/k8s/"
