name: Deploy to Kubernetes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Infra"]  # ✅ Run after Infra pipeline
    types:
      - completed

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # ✅ Download Infra Artifacts from previous workflow run
      - name: Download Infra Artifacts
        uses: actions/download-artifact@v4
        with:
          name: k8s-artifacts
          path: infra/

      - name: Verify Artifacts
        run: |
          echo "[INFO] Artifacts downloaded:"
          ls -l infra/
          cat infra/instance_ips.txt

      - name: Install SSH Client & kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass curl
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy Kubernetes Manifests
        run: |
          MASTER_IP=$(head -n 1 infra/instance_ips.txt)
          echo "[INFO] Connecting to Master Node: $MASTER_IP"
          chmod 400 infra/k8s-key.pem

          # ✅ Copy manifests to master node
          scp -o StrictHostKeyChecking=no -i infra/k8s-key.pem ./k8s/*.yaml ubuntu@$MASTER_IP:/home/ubuntu/

          # ✅ Apply manifests remotely
          ssh -o StrictHostKeyChecking=no -i infra/k8s-key.pem ubuntu@$MASTER_IP << 'EOF'
            echo "[INFO] Applying Kubernetes manifests..."
            kubectl apply -f /home/ubuntu/
            echo "[INFO] Kubernetes deployment completed."
          EOF
