name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types:
      - completed
  push:
    paths:
      - 'k8s/**'

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Infra State
        run: |
          git fetch origin infra-state
          git checkout infra-state -- infra-state/
          MASTER_IP=$(head -n 1 infra-state/instance_ips.txt)
          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          chmod 600 infra-state/k8s-key.pem
          ssh -o StrictHostKeyChecking=no -i infra-state/k8s-key.pem ubuntu@$MASTER_IP "
            kubectl apply -f /home/ubuntu/k8s/
          "
