name: Deploy with Helm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    name: Deploy Microservices via Helm
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout current branch (main)
        uses: actions/checkout@v3

      - name: ✅ Checkout `infra-state` folder from `infra-state` branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: infra-state
          path: infra-tmp
          sparse-checkout: |
            infra-state/
          sparse-checkout-cone-mode: false

      - name: ✅ Move infra-state files to root
        run: |
          mv infra-tmp/infra-state ./infra-state

      - name: ✅ Extract first master node IP
        run: |
          IPS=$(cat infra-state/instance_ips.txt)
          KEY="infra-state/k8s-key.pem"
          chmod 600 $KEY
          FIRST_NODE=$(head -n1 infra-state/instance_ips.txt)
          echo "FIRST_NODE=$FIRST_NODE" >> $GITHUB_ENV

      - name: ✅ Copy Helm charts to master node
        run: |
          echo "[INFO] Copying Helm charts to $FIRST_NODE"
          scp -o StrictHostKeyChecking=no -i infra-state/k8s-key.pem -r helm ubuntu@$FIRST_NODE:/home/ubuntu/helm

      - name: ✅ Deploy Helm charts
        run: |
          ssh -o StrictHostKeyChecking=no -i infra-state/k8s-key.pem ubuntu@$FIRST_NODE "
            echo '[INFO] Installing Helm if not present...'
            if ! command -v helm &> /dev/null; then
              sudo snap install helm --classic
            fi

            echo '[INFO] Deploying microservices using Helm...'
            cd /home/ubuntu/helm
            for chart in catalogue frontend recommendation voting; do
              helm upgrade --install \$chart ./\$chart
            done

            echo '[INFO] Waiting for pods to be ready...'
            sleep 10
            kubectl get pods -A
          "
        env:
          FIRST_NODE: ${{ env.FIRST_NODE }}
