name: Deploy with Helm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    name: Deploy Microservices via Helm
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout main branch (includes helm folder)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: ✅ Checkout `infra-state` folder from `infra-state` branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: infra-state
          path: infra-tmp
          sparse-checkout: |
            infra-state/
          sparse-checkout-cone-mode: false

      - name: ✅ Move infra-state files to root
        run: |
          mv infra-tmp/infra-state ./infra-state

      - name: ✅ Extract master node IP
        run: |
          KEY="infra-state/k8s-key.pem"
          chmod 600 $KEY
          FIRST_NODE=$(head -n1 infra-state/instance_ips.txt)
          echo "FIRST_NODE=$FIRST_NODE" >> $GITHUB_ENV

      - name: ✅ Ensure Helm charts exist
        run: |
          if [ ! -d "helm" ]; then
            echo "❌ 'helm/' directory not found!"
            exit 1
          fi

      - name: ✅ Copy Helm charts to master node
        run: |
          echo "[INFO] Copying Helm charts to $FIRST_NODE"
          scp -o StrictHostKeyChecking=no -i infra-state/k8s-key.pem -r helm ubuntu@$FIRST_NODE:/home/ubuntu/helm

      - name: ✅ Deploy Helm charts on master node
        run: |
          ssh -o StrictHostKeyChecking=no -i infra-state/k8s-key.pem ubuntu@$FIRST_NODE "
            echo '[INFO] Installing Helm if not present...'
            if ! command -v helm &> /dev/null; then
              sudo snap install helm --classic
            fi

            echo '[INFO] Deploying Helm charts...'
            cd /home/ubuntu/helm

            # Deploy all microservices
            for svc in catalogue frontend recommendation voting; do
              if [ -d \"\$svc\" ]; then
                helm upgrade --install \$svc ./\$svc
              else
                echo \"⚠️ Chart folder \$svc not found, skipping\"
              fi
            done

            echo '[INFO] Waiting for pods to be ready...'
            sleep 10
            sudo microk8s kubectl get pods -A
          "
