name: Infra, Build & Deploy Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_provision:
    name: Provision Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          cd infra/
          terraform init
          terraform apply -auto-approve

      # ✅ Step 1: Try Terraform Outputs with Retry
      - name: Extract Terraform Outputs
        id: extract_tf
        continue-on-error: true
        run: |
          cd infra/
          sudo apt-get update && sudo apt-get install -y jq
          
          echo "Attempting Terraform output extraction with retries..."
          success=false
          for i in {1..10}; do
            if terraform output -json > outputs.json 2>/dev/null && jq empty outputs.json; then
              echo "Valid JSON detected"
              jq -r '.instance_ips.value[]' outputs.json > instance_ips.txt
              terraform output -raw private_key > k8s-key.pem
              chmod 600 k8s-key.pem
              success=true
              break
            else
              echo "Attempt $i: Invalid JSON, retrying in 10s..."
              sleep 10
            fi
          done

          if [ "$success" = false ]; then
            echo "Terraform output failed after retries"
            exit 1
          fi

      # ✅ Step 2: AWS CLI Fallback if Step 1 failed
      - name: AWS CLI Fallback for IP Extraction
        if: steps.extract_tf.outcome == 'failure'
        run: |
          echo "Terraform output failed, switching to AWS CLI fallback..."
          
          # Check if AWS CLI is installed
          if aws --version >/dev/null 2>&1; then
            echo "AWS CLI already installed, skipping installation"
          else
            echo "Installing AWS CLI v2..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          fi

          echo "Fetching instance IPs using AWS CLI..."
          mkdir -p infra
          aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=k8s-master,k8s-worker-*" \
            --query 'Reservations[].Instances[].PublicIpAddress' \
            --output text | tr '\t' '\n' > infra/instance_ips.txt
          
          if [ -s infra/instance_ips.txt ]; then
            echo "AWS CLI fallback successful"
          else
            echo "AWS CLI fallback failed!"
            exit 1
          fi

      - name: Upload Artifacts for Next Job
        uses: actions/upload-artifact@v4
        with:
          name: k8s-artifacts
          path: |
            infra/k8s-key.pem
            infra/instance_ips.txt

  docker_build_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: terraform_provision
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Images
        run: |
          docker build -t $REGISTRY:frontend-latest ./frontend
          docker push $REGISTRY:frontend-latest

          docker build -t $REGISTRY:catalogue-latest ./catalogue
          docker push $REGISTRY:catalogue-latest

          docker build -t $REGISTRY:voting-latest ./voting
          docker push $REGISTRY:voting-latest

          docker build -t $REGISTRY:recommendation-latest ./recommendation
          docker push $REGISTRY:recommendation-latest

  deploy_to_k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [docker_build_push]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download SSH Key & IPs
        uses: actions/download-artifact@v4
        with:
          name: k8s-artifacts
          path: ./infra

      - name: Install SSH Client
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          chmod 600 infra/k8s-key.pem

      - name: Setup Kubernetes Cluster via SSH
        run: |
          MASTER_IP=$(sed -n '1p' infra/instance_ips.txt)
          WORKER1_IP=$(sed -n '2p' infra/instance_ips.txt)
          WORKER2_IP=$(sed -n '3p' infra/instance_ips.txt)

          echo "Master: $MASTER_IP, Worker1: $WORKER1_IP, Worker2: $WORKER2_IP"

          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no infra/install_docker.sh ubuntu@$MASTER_IP:/home/ubuntu/
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no infra/kube-install.sh ubuntu@$MASTER_IP:/home/ubuntu/

          ssh -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "bash install_docker.sh && bash kube-install.sh $WORKER1_IP $WORKER2_IP"

      - name: Deploy Microservices
        run: |
          mkdir -p ~/.kube
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$(sed -n '1p' infra/instance_ips.txt):/home/ubuntu/admin.conf ~/.kube/config
          export KUBECONFIG=~/.kube/config
          kubectl apply -f k8s-manifests/

  destroy_infra:
    name: Rollback Infra if Failed
    runs-on: ubuntu-latest
    if: failure()
    needs: [terraform_provision, docker_build_push, deploy_to_k8s]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Infra
        run: |
          cd infra/
          terraform init
          terraform destroy -auto-approve
