name: Build, Deploy & Infra Provision

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'frontend/**'
      - 'catalogue/**'
      - 'voting/**'
      - 'recommendation/**'
      - 'k8s-manifests/**'
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    if: contains(join(github.event.head_commit.modified, ','), 'infra/')
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          cd infra
          terraform init
          terraform apply -auto-approve
      - name: Export Private Key
        run: |
          echo "${{ steps.terraform.outputs.private_key }}" > k8s.pem
          chmod 600 k8s.pem

  docker_build_push:
    needs: terraform_provision
    runs-on: ubuntu-latest
    if: contains(join(github.event.head_commit.modified, ','), 'frontend/') ||
        contains(join(github.event.head_commit.modified, ','), 'catalogue/') ||
        contains(join(github.event.head_commit.modified, ','), 'voting/') ||
        contains(join(github.event.head_commit.modified, ','), 'recommendation/')
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build & Push Images
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"frontend"* ]]; then
            docker build -t $REGISTRY:frontend-latest ./frontend
            docker push $REGISTRY:frontend-latest
          fi
          if [[ "${{ github.event.head_commit.message }}" == *"catalogue"* ]]; then
            docker build -t $REGISTRY:catalogue-latest ./catalogue
            docker push $REGISTRY:catalogue-latest
          fi
          if [[ "${{ github.event.head_commit.message }}" == *"voting"* ]]; then
            docker build -t $REGISTRY:voting-latest ./voting
            docker push $REGISTRY:voting-latest
          fi
          if [[ "${{ github.event.head_commit.message }}" == *"recommendation"* ]]; then
            docker build -t $REGISTRY:recommendation-latest ./recommendation
            docker push $REGISTRY:recommendation-latest
          fi

  deploy_to_k8s:
    needs: docker_build_push
    runs-on: ubuntu-latest
    if: contains(join(github.event.head_commit.modified, ','), 'k8s-manifests/')
    steps:
      - uses: actions/checkout@v3
      - name: Generate kubeconfig
        run: |
          ssh -i infra/k8s.pem -o StrictHostKeyChecking=no ubuntu@$(terraform output -raw master_public_ip) "cat /etc/kubernetes/admin.conf" > ~/.kube/config
      - name: Deploy
        run: kubectl apply -f k8s-manifests/
