name: Build, Deploy & Infra Provision

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - 'frontend/**'
      - 'catalogue/**'
      - 'voting/**'
      - 'recommendation/**'
      - 'k8s-manifests/**'
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_provision:
    name: "Provision Infra with Terraform"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip terraform]') == false
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || startsWith(join(github.event.head_commit.modified, ','), 'terraform/')
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

  docker_build_push:
    name: "Build & Push Docker Images"
    needs: terraform_provision
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || 
        contains(join(github.event.head_commit.modified, ','), 'frontend/') || 
        contains(join(github.event.head_commit.modified, ','), 'catalogue/') || 
        contains(join(github.event.head_commit.modified, ','), 'voting/') || 
        contains(join(github.event.head_commit.modified, ','), 'recommendation/')
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend
        if: contains(join(github.event.head_commit.modified, ','), 'frontend/')
        run: |
          docker build -t $REGISTRY:frontend-latest ./frontend
          docker push $REGISTRY:frontend-latest

      - name: Build & Push Catalogue
        if: contains(join(github.event.head_commit.modified, ','), 'catalogue/')
        run: |
          docker build -t $REGISTRY:catalogue-latest ./catalogue
          docker push $REGISTRY:catalogue-latest

      - name: Build & Push Voting
        if: contains(join(github.event.head_commit.modified, ','), 'voting/')
        run: |
          docker build -t $REGISTRY:voting-latest ./voting
          docker push $REGISTRY:voting-latest

      - name: Build & Push Recommendation
        if: contains(join(github.event.head_commit.modified, ','), 'recommendation/')
        run: |
          docker build -t $REGISTRY:recommendation-latest ./recommendation
          docker push $REGISTRY:recommendation-latest

  deploy_to_k8s:
    name: "Deploy to Kubernetes"
    needs: docker_build_push
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(join(github.event.head_commit.modified, ','), 'k8s-manifests/')
    steps:
      - uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s-manifests/
