name: Build, Deploy & Infra Provision

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'frontend/**'
      - 'catalogue/**'
      - 'voting/**'
      - 'recommendation/**'
      - 'k8s-manifests/**'
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_provision:
    name: "Provision Infra with Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve

      - name: Upload SSH Private Key
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: terraform/k8s-key.pem

      - name: Show Instance IPs
        run: cat terraform/instance_ips.txt

      - name: Upload Instance IPs
        uses: actions/upload-artifact@v4
        with:
          name: instance-ips
          path: terraform/instance_ips.txt

  docker_build_push:
    name: "Build and Push Docker Images"
    needs: terraform_provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t $REGISTRY:frontend-latest ./frontend
          docker push $REGISTRY:frontend-latest

      - name: Build and Push Catalogue
        run: |
          docker build -t $REGISTRY:catalogue-latest ./catalogue
          docker push $REGISTRY:catalogue-latest

      - name: Build and Push Voting
        run: |
          docker build -t $REGISTRY:voting-latest ./voting
          docker push $REGISTRY:voting-latest

      - name: Build and Push Recommendation
        run: |
          docker build -t $REGISTRY:recommendation-latest ./recommendation
          docker push $REGISTRY:recommendation-latest

  deploy_to_k8s:
    name: "Deploy to Kubernetes"
    needs: docker_build_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download SSH Key
        uses: actions/download-artifact@v4
        with:
          name: ssh-key
          path: ~/.ssh/

      - name: Set Permissions
        run: chmod 600 ~/.ssh/k8s-key.pem

      - name: Download Instance IPs
        uses: actions/download-artifact@v4
        with:
          name: instance-ips
          path: .

      - name: Setup SSH Config
        run: |
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Install Kubernetes on Cluster
        run: |
          MASTER_IP=$(head -n 1 instance_ips.txt)
          ssh -i ~/.ssh/k8s-key.pem ubuntu@$MASTER_IP 'bash -_
