name: Build, Deploy & Infra Provision

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - 'frontend/**'
      - 'catalogue/**'
      - 'voting/**'
      - 'recommendation/**'
      - 'k8s-manifests/**'
  workflow_dispatch:

env:
  REGISTRY: kmn1624/craftista
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_provision:
    name: "Provision Infra with Terraform"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-infra]') == false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve

  docker_build_push:
    name: "Build and Push Docker Images"
    needs: terraform_provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v3

      - name: Docker Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push All Services
        run: |
          if [ -d "frontend" ]; then
            docker build -t $REGISTRY:frontend-latest ./frontend && docker push $REGISTRY:frontend-latest
          fi
          if [ -d "catalogue" ]; then
            docker build -t $REGISTRY:catalogue-latest ./catalogue && docker push $REGISTRY:catalogue-latest
          fi
          if [ -d "voting" ]; then
            docker build -t $REGISTRY:voting-latest ./voting && docker push $REGISTRY:voting-latest
          fi
          if [ -d "recommendation" ]; then
            docker build -t $REGISTRY:recommendation-latest ./recommendation && docker push $REGISTRY:recommendation-latest
          fi

  deploy_to_k8s:
    name: "Deploy to Kubernetes"
    needs: docker_build_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy All Microservices
        run: kubectl apply -f k8s-manifests/
