name: Deploy Kubernetes on Existing Infra

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest
    env:
      REGISTRY: kmn1624/craftista
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate infra folder
        run: |
          if [ ! -f infra/instance_ips.txt ] || [ ! -f infra/k8s-key.pem ]; then
            echo "[ERROR] Required files (instance_ips.txt or k8s-key.pem) missing!"
            exit 1
          fi
          chmod 600 infra/k8s-key.pem

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Read IPs and SSH into Master
        run: |
          MASTER_IP=$(sed -n '1p' infra/instance_ips.txt)
          WORKER1_IP=$(sed -n '2p' infra/instance_ips.txt)
          WORKER2_IP=$(sed -n '3p' infra/instance_ips.txt)

          echo "[INFO] Using existing infra:"
          echo "Master: $MASTER_IP"
          echo "Worker1: $WORKER1_IP"
          echo "Worker2: $WORKER2_IP"

          # Check SSH connectivity
          for i in {1..15}; do
            if ssh -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "echo connected"; then
              echo "[INFO] SSH Connected."
              break
            fi
            echo "[WARN] SSH attempt $i failed. Retrying in 10s..."
            sleep 10
          done

      - name: Copy and Execute K8s Scripts
        run: |
          MASTER_IP=$(sed -n '1p' infra/instance_ips.txt)
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no infra/install_docker.sh ubuntu@$MASTER_IP:/home/ubuntu/
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no infra/kube-install.sh ubuntu@$MASTER_IP:/home/ubuntu/
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no infra/k8s-key.pem ubuntu@$MASTER_IP:/home/ubuntu/k8s-key.pem

          ssh -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP \
            "chmod +x install_docker.sh kube-install.sh && sudo bash install_docker.sh && sudo bash kube-install.sh"

      - name: Deploy Microservices to Kubernetes
        run: |
          MASTER_IP=$(sed -n '1p' infra/instance_ips.txt)
          echo "[INFO] Copying manifests to Master..."
          scp -i infra/k8s-key.pem -o StrictHostKeyChecking=no -r manifests ubuntu@$MASTER_IP:/home/ubuntu/

          echo "[INFO] Applying manifests..."
          ssh -i infra/k8s-key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP \
            "kubectl apply -f manifests/"
