name: Provision Infra

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform_provision.yaml'

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: cd infra && terraform init

      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve

      - name: Extract IPs & Prepare Files
        run: |
          cd infra
          terraform output -json instance_ips | jq -r '.value[]' > instance_ips.txt
          chmod 400 k8s-key.pem
          echo "[INFO] Extracted IPs:"
          cat instance_ips.txt

      - name: Upload Infra Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra-files
          path: |
            infra/instance_ips.txt
            infra/k8s-key.pem
