name: Provision Infrastructure

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve || { echo "[ERROR] Destroying infra..."; terraform destroy -auto-approve; exit 1; }

      - name: Extract & Commit Infra State
        run: |
          cd infra
          terraform output -json > outputs.json
          jq -r '.instance_ips.value[]?' outputs.json > instance_ips.txt
          jq -r '.private_key.value' outputs.json > k8s-key.pem
          chmod 600 k8s-key.pem

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout infra-state || git checkout --orphan infra-state
          mkdir -p infra-state
          cp instance_ips.txt k8s-key.pem infra-state/
          git add infra-state/
          git commit -m "Update infra state"
          git push origin infra-state --force
