name: Infra

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  REGISTRY: kmn1624/craftista

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          cd infra/
          terraform init
          terraform apply -auto-approve

      - name: Extract Terraform Outputs
        run: |
          cd infra/
          terraform output -json > outputs.json
          jq -r '.instance_ips.value[]' outputs.json > instance_ips.txt
          jq -r '.private_key.value' outputs.json > k8s-key.pem
          chmod 600 k8s-key.pem
          echo "[INFO] Extracted IPs:"
          cat instance_ips.txt

      - name: Upload Artifacts for Next Jobs
        uses: actions/upload-artifact@v4
        with:
          name: k8s-artifacts
          path: |
            infra/k8s-key.pem
            infra/instance_ips.txt
