name: Provision Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yaml'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  REGISTRY: kmn1624/craftista

jobs:
  terraform_provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Extract Terraform Outputs with Validation
        run: |
          cd infra
          echo "[INFO] Attempting Terraform output extraction..."
          OUTPUT=$(terraform output -json || echo "")

          # Validate if OUTPUT is empty or invalid JSON
          if [ -z "$OUTPUT" ] || ! echo "$OUTPUT" | jq empty >/dev/null 2>&1; then
            echo "[ERROR] Terraform outputs are invalid or empty. Please check your main.tf outputs."
            exit 1
          fi

          # Save valid output to file
          echo "$OUTPUT" > outputs.json

          # Extract instance IPs
          INSTANCE_IPS=$(echo "$OUTPUT" | jq -r '.instance_ips.value[]?')
          if [ -z "$INSTANCE_IPS" ]; then
            echo "[ERROR] No instance IPs found in Terraform output."
            exit 1
          fi
          echo "$INSTANCE_IPS" > instance_ips.txt

          # Extract private key
          PRIVATE_KEY=$(echo "$OUTPUT" | jq -r '.private_key.value // empty')
          if [ -z "$PRIVATE_KEY" ]; then
            echo "[ERROR] Private key not found in Terraform output."
            exit 1
          fi
          echo "$PRIVATE_KEY" > k8s-key.pem
          chmod 600 k8s-key.pem

          echo "[INFO] Extracted IPs:"
          cat instance_ips.txt

      - name: Upload Infra Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-artifacts
          path: |
            infra/instance_ips.txt
            infra/k8s-key.pem
