name: Provision Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/provision_infra.yaml'
  workflow_dispatch:

jobs:
  terraform_provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        id: apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Extract IPs & Save Key
        if: success()
        run: |
          cd infra
          terraform output -json instance_ips | jq -r '.[]' > instance_ips.txt
          cp k8s-key.pem ./k8s-key.pem

      - name: Push Infra State to infra-state Branch
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout --orphan infra-state || git checkout infra-state
          mkdir -p infra
          cp infra/instance_ips.txt infra/k8s-key.pem infra/
          git add infra/*
          git commit -m "Update infra files"
          git push origin infra-state --force

      - name: Destroy on Failure
        if: failure()
        run: |
          cd infra
          terraform destroy -auto-approve
