name: Provision Infrastructure

on:
  push:
    paths:
      - 'infra/**'
      - 'main.tf'
  workflow_dispatch:

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Extract IPs and Key
        run: |
          cd infra
          terraform output -json > outputs.json
          jq -r '.instance_ips.value[]' outputs.json > instance_ips.txt
          jq -r '.private_key.value' outputs.json > k8s-key.pem
          chmod 600 k8s-key.pem
          echo "[INFO] Extracted IPs:"
          cat instance_ips.txt

      - name: Commit Artifacts to infra-state Branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan infra-state
          git reset
          mkdir -p infra-state
          cp infra/instance_ips.txt infra/k8s-key.pem infra-state/
          git add infra-state/*
          git commit -m "Update infra artifacts"
          git push origin HEAD:infra-state --force
