name: Provision Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform_provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: cd infra && terraform init

      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve

      - name: Extract Instance IPs
        run: |
          cd infra
          terraform output -json instance_ips | jq -r '.[]' > instance_ips.txt

      - name: Upload Infra Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: infra-files
          path: |
            infra/instance_ips.txt
            infra/k8s-key.pem
